export const someoneArray = ["They think you can be described as charismatic.",
"They know that you are glamorous.",
"They find you very exciting.",
"They think that you tend to be remarkably tough. You can break through any problem.",
"They think that you are quite rational.",
"They think you are very exciting.",
"They think that you tend to be remarkably colorful.",
"They think that you tend to be personable.",
"They think that you tend to be sympathetic.",
"They think that you are pretty trusting. Be careful who you trust without changing yourself.",
"They think that you are quite daring.",
"They think that you tend to be exciting.",
"They think that you are quite methodical.",
"They think that you tend to be remarkably empathetic.",
"They think you are very idiosyncratic.",
"They think that you are pretty humorous.",
"They think you can be described as graceful. Your friends admire you.",
"They think that you are quite impressionable.",
"They find you very reflective.",
"They think that you are quite maternal.",
"They think that you are quite compassionate.",
"They think that you tend to be remarkably humorous.",
"They think you are very stable.",
"They think that you tend to be too transparent sometimes. Keep in mind white lies don't hurt.",
"They think that you are pretty humorous.",
"They think that you are pretty optimistic.",
"They find you very amusing.",
"They think that you tend to be innovative.",
"They find you very artful.",
"They think that you tend to be sociable.",
"They think you can be described as impulsive. Think better before you make decisions and your life will change dramatically.",
"They think that you are pretty irreverent.",
"They think you are very iconoclastic.",
"They find you very focused.",
"They know that you are ascetic.",
"They think that you tend to be remarkably brilliant.",
"They know that you are dry humored sometimes.",
"They think that you tend to be impassive.",
"They find you very focused.",
"They think that you are pretty calm.",
"They think you can be described as steady.",
"They think you are very charismatic.",
"They think that you are pretty personable.",
"They find you very freewheeling.",
"They think that you tend to be remarkably steady.",
"They think you can be described as dreamy, but it's good. Keep dreaming they will come true.",
"They think that you tend to be compassionate.",
"They think that you tend to be remarkably conscientious.",
"They think you can be described as unaggressive. Always stay that way.",
"They think that you tend to be irreverent.",
"They think that you tend to be remarkably respectful.",
"They think you can be ambitious.",
"They know that you are whimsical, people around you think you are a delight.",
"They think that you tend to be wise even if you don't know it. Your take on things is insightful.",
"They find you very peaceful.",
"They think that you are pretty captivating.",
"They think you can be described as warm.",
"They think that you are pretty strong.",
"They think that you are pretty idealistic.",
"They know that you are intense.",
"They think you can be big-thinking.",
"They think that you are quite maternal.",
"They think you are very perceptive.",
"They think that you tend to be loyal.",
"They think you can be fun-loving.",
"They think you can be described as personable.",
"They think that you tend to be remarkably delightful.",
"They think you are very tense about a relationship in your life but trust me there's nothing to worry.",
"They find you very self-reliant.",
"They think you are very maternal.",
"They think you are very eloquent.",
"They think you can be big-thinking.",
"They think you can be described as wishful.",
"They know that you are caring.",
"They think that you tend to be remarkably an unpolished gem.",
"They think that you are quite earthy.",
"They think that you are pretty self-reliant.",
"They know that you are steady.",
"They think that you are quite unpredictable in others' eyes. People find that intriguing about you.",
"They think you can be described as personable.",
"They think you can be clean.",
"They think you can be described as enthusiastic.",
"They think you can be described as mellow.",
"They know that you are folksy.",
"They know that you are eloquent.",
"They think that you tend to be optimistic.",
"They find you very undisciplined about certain habits and you know it. Try to fix those and things will flow.",
"They think you are very mellow.",
"They know that you are unpredictable in others' eyes. People find that intriguing about you.",
"They think that you tend to be enthusiastic.",
"They think that you tend to be charismatic.",
"They think you can be skillful.",
"They think that you tend to be confident.",
"They know that you are confident.",
"They find you very independent.",
"They find you very exciting.",
"They think you can be esthetic.",
"They find you very unaggressive. Always stay that way.",
"They think that you are quite high-spirited.",
"They think you can be clean.",
"They think you can be rational.",
"They find you very winning.",
"They think that you are pretty friendly.",
"They think that you tend to be remarkably reflective.",
"They know that you are guileless.",
"They think that you tend to be remarkably daring.",
"They think that you tend to be remarkably admirable.",
"They think you can be described as fun-loving.",
"They think that you tend to be objective.",
"They think you can be winning.",
"They think you can be reliable.",
"They think you can be winning.",
"They think that you tend to be remarkably strong.",
"They think that you are pretty hearty.",
"They think you can be described as high-spirited.",
"They think you can be mature.",
"They think that you tend to be remarkably family-oriented.",
"They think that you are pretty individualistic.",
"They think you are very calm.",
"They think that you are pretty skillful.",
"They think you are very reflective.",
"They think you are very tough. You can break through any problem.",
"They think that you are pretty curious.",
"They think that you tend to be remarkably considerate.",
"They think you can be compassionate.",
"They think that you are pretty exciting.",
"They find you very impressionable.",
"They think you can be maternal.",
"They think that you tend to be fun-loving.",
"They think you are very strong.",
"They know that you are intuitive.",
"They think that you are quite personable.",
"They think that you are pretty artful.",
"They think that you tend to be remarkably stubborn. Any problem you have eventually gets resolved.",
"They think you are very maternal.",
"They think you are very admirable.",
"They find you very earthy.",
"They know that you are energetic.",
"They think you can be irreverent.",
"They think that you tend to be remarkably many-sided.",
"They think you are very calm.",
"They think that you tend to be remarkably forgiving.",
"They think you can be observant.",
"They think you can be described as well-rounded.",
"They think you can be whimsical, people around you think you are a delight.",
"They think that you tend to be humble.",
"They find you very peaceful.",
"They find you very reflective.",
"They know that you are curious.",
"They think that you tend to be remarkably graceful. Your friends admire you.",
"They think that you tend to be frugal.",
"They think that you are quite idiosyncratic.",
"They think that you tend to be modern.",
"They think you can be described as reliable and gentle. Your friends find you comforting.",
"They know that you are perceptive.",
"They think you are very humorous.",
"They find you very rational.",
"They find you very independent.",
"They think that you tend to be wise even if you don't know it. Your take on things is insightful.",
"They think that you are pretty conscientious.",
"They think that you tend to be remarkably cerebral. People around you admire your intelligence.",
"They think you can be described as energetic.",
"They know that you are optimistic.",
"They think that you tend to be determined. Never give up on what you love.",
"They think that you tend to be clever.",
"They know that you are high-spirited.",
"They think that you are quite innovative.",
"They think that you tend to be extraordinary.",
"They think that you are quite forgiving.",
"They know that you are intuitive.",
"They think you can be described as impressive.",
"They think that you are pretty maternal.",
"They think that you are quite humble.",
"They think that you are pretty humble.",
"They think you can be described as reliable and gentle. Your friends find you comforting.",
"They think that you are quite hypnotic.",
"They think you can be charming.",
"They think you can be described as delightful.",
"They think that you are pretty a trend setter but you don't know it. be careful who you influence around you.",
"They think you are very persuasive.",
"They think that you are quite vulnerable to ill-meaning people because you tend to be too trusting sometimes. Trust with caution.",
"They think you can be rational.",
"They find you very impassive.",
"They think you can be freethinking.",
"They think that you tend to be remarkably eloquent.",
"They think that you tend to be remarkably wishful.",
"They think that you tend to be remarkably frugal.",
"They think that you are pretty caring.",
"They think you are very independent.",
"They find you very idealistic.",
"They think that you are quite brilliant.",
"They know that you are rigid about the things you don't like in a person. Maybe if you let go of some of these you could see a different side to people.",
"They find you very peaceful.",
"They think that you tend to be remarkably sociable.",
"They find you very idiosyncratic.",
"They think that you are pretty peaceful.",
"They think that you tend to be remarkably open.",
"They think you can be described as charismatic.",
"They think you can be described as experimental.",
"They think that you are quite dry humored sometimes.",
"They think you can be too transparent sometimes. Keep in mind white lies don't hurt.",
"They find you very complex. I admire you.",
"They think you are very emotional.",
"They think that you tend to be principled.",
"They think that you are quite clean.",
"They know that you are charming.",
"They think that you tend to be individualistic.",
"They find you very clean.",
"They think that you are quite idiosyncratic.",
"They think that you tend to be remarkably daring.",
"They think that you tend to be caring.",
"They think that you are quite high-spirited.",
"They think that you tend to be caring.",
"They think that you tend to be earthy.",
"They think you can be humble.",
"They think that you tend to be remarkably dedicated.",
"They think that you are quite an unpolished gem.",
"They think you are very sympathetic.",
"They find you very hearty.",
"They think that you are quite friendly.",
"They think you can be described as a trend setter but you don't know it. be careful who you influence around you.",
"They think that you tend to be wise even if you don't know it. Your take on things is insightful.",
"They find you very impulsive. Think better before you make decisions and your life will change dramatically.",
"They think you can be described as sensitive.",
"They think that you are pretty conscientious.",
"They think you can be freethinking.",
"They think that you are quite steady.",
"They think that you tend to be personable.",
"They think that you are quite steady.",
"They find you very stubborn. Any problem you have eventually gets resolved.",
"They think you are very independent.",
"They think that you are quite logical.",
"They think that you are pretty modern.",
"They think you can be possessive over the people you love but that's okay in small doses.",
"They think that you are pretty energetic.",
"They find you very perceptive.",
"They think you can be described as sensitive.",
"They think that you tend to be remarkably undisciplined about certain habits and you know it. Try to fix those and things will flow.",
"They think that you tend to be remarkably freethinking.",
"They think that you tend to be remarkably unrealistic about the dreams of the people you love.",
"They think that you are pretty maternal.",
"They think you are very exciting.",
"They think that you are quite huried.",
"They think that you tend to be remarkably humorous.",
"They think that you are pretty compassionate.",
"They know that you are hardworking.",
"They think that you tend to be dedicated.",
"They think you are very maternal.",
"They think that you are pretty admirable.",
"They think that you are quite passionate.",
"They think you can be idealistic.",
"They think you can be described as folksy.",
"They think you are very maternal.",
"They think that you tend to be remarkably admirable.",
"They find you very honest.",
"They find you very open.",
"They think you can be admirable.",
"They find you very considerate.",
"They think that you tend to be remarkably fun-loving.",
"They think that you are pretty hypnotic.",
"They find you very artful.",
"They think you can be optimistic.",
"They think you can be described as humorous.",
"They think you can be described as persuasive.",
"They think you are very moralistic. Keep that in mind when you make decisions.",
"They find you very caring.",
"They think you are very intuitive.",
"They think you are very a trend setter but you don't know it. be careful who you influence around you.",
"They think you are very clean.",
"They think that you are quite forgetful. Just take more notes of things that matter.",
"They think you can be described as stable.",
"They think that you tend to be shy.",
"They think you are very realistic.",
"They know that you are insightful.",
"They think you can be hypnotic.",
"They find you very rational.",
"They think that you tend to be remarkably clever.",
"They think you can be irreverent.",
"They think that you are pretty many-sided.",
"They find you very hypnotic.",
"They think that you tend to be self-reliant.",
"They know that you are huried.",
"They think that you are pretty sophisticated.",
"They think you are very self-sufficient.",
"They think you can be cheerful.",
"They know that you are family-oriented.",
"They think you can be naive. But that makes you you.",
"They think that you tend to be protective.",
"They think that you tend to be remarkably impressionable.",
"They think that you are quite tense about a relationship in your life but trust me there's nothing to worry.",
"They think that you are quite skillful.",
"They think that you tend to be remarkably daring.",
"They know that you are folksy.",
"They know that you are ambitious.",
"They think you can be described as hypnotic.",
"They find you very humorous.",
"They know that you are irreverent.",
"They think that you tend to be tense about a relationship in your life but trust me there's nothing to worry.",
"They think that you tend to be well-rounded.",
"They think you are very skillful.",
"They know that you are naive. But that makes you you.",
"They think that you are pretty warm.",
"They know that you are irreverent.",
"They think you can be described as freethinking.",
"They think you are very mature.",
"They think you are very persuasive.",
"They think you can be described as sensitive.",
"They know that you are imaginative.",
"They think that you tend to be tough. You can break through any problem.",
"They think that you tend to be remarkably too transparent sometimes. Keep in mind white lies don't hurt.",
"They know that you are fun-loving.",
"They find you very unrestrained. You live your life freely.",
"They think that you are pretty emotional.",
"They find you very impressive.",
"They think you are very freewheeling.",
"They think that you tend to be remarkably tense about a relationship in your life but trust me there's nothing to worry.",
"They think that you tend to be so thoughtful and know that your friends appreciate that very much.",
"They think you are very guileless.",
"They know that you are clever.",
"They find you very daring.",
"They think that you are pretty high-spirited.",
"They think you are very dreamy, but it's good. Keep dreaming they will come true.",
"They think that you are pretty daring.",
"They know that you are elegant.",
"They think that you tend to be remarkably imaginative.",
"They think you can be objective.",
"They think that you tend to be remarkably colorful.",
"They think you can be described as admirable.",
"They think that you tend to be remarkably clean.",
"They think you can be described as vulnerable to ill-meaning people because you tend to be too trusting sometimes. Trust with caution.",
"They think that you are pretty tense about a relationship in your life but trust me there's nothing to worry.",
"They find you very ascetic.",
"They think you can be described as personable.",
"They think you can be unaggressive. Always stay that way.",
"They think you are very unimaginative sometimes but you have it in you to dream bigger.",
"They think that you tend to be moralistic. Keep that in mind when you make decisions.",
"They think that you tend to be remarkably spontaneous.",
"They think you can be described as daring.",
"They think that you are pretty folksy.",
"They think that you tend to be impulsive. Think better before you make decisions and your life will change dramatically.",
"They know that you are idiosyncratic.",
"They find you very ambitious.",
"They find you very self-reliant.",
"They think that you tend to be remarkably lovable. People love to be around you.",
"They think you can be described as helpful.",
"They find you very wishful.",
"They think that you are quite hypnotic.",
"They think that you are pretty modern.",
"They think you are very objective.",
"They know that you are unpredictable in others' eyes. People find that intriguing about you.",
"They think that you are pretty amusing.",
"They think that you are pretty creative.",
"They think you are very amusing.",
"They think you can be objective.",
"They think that you tend to be remarkably insightful.",
"They think that you tend to be remarkably tense about a relationship in your life but trust me there's nothing to worry.",
"They think that you are quite complex. I admire you.",
"They think you can be tough. You can break through any problem.",
"They think you can be described as methodical.",
"They think you are very vulnerable to ill-meaning people because you tend to be too trusting sometimes. Trust with caution.",
"They think that you are pretty admirable.",
"They think you are very irreverent.",
"They think that you tend to be remarkably principled.",
"They think that you are pretty ambitious.",
"They think that you tend to be remarkably folksy.",
"They think that you tend to be remarkably considerate.",
"They think you can be respectful.",
"They think you are very intense.",
"They think you are very frugal.",
"They think you can be described as complex. I admire you.",
"They know that you are ascetic.",
"They find you very charismatic.",
"They think you can be described as emotional.",
"They think that you tend to be graceful. Your friends admire you.",
"They find you very delightful.",
"They think you can be described as principled.",
"They know that you are wise even if you don't know it. Your take on things is insightful.",
"They think that you are quite modern.",
"They think that you tend to be remarkably elegant.",
"They find you very stubborn. Any problem you have eventually gets resolved.",
"They find you very self-reliant.",
"They know that you are guileless.",
"They think that you tend to be too transparent sometimes. Keep in mind white lies don't hurt.",
"They know that you are unpredictable in others' eyes. People find that intriguing about you.",
"They think that you are quite earthy.",
"They think that you tend to be remarkably intense.",
"They think that you are pretty fun-loving.",
"They think that you tend to be sympathetic.",
"They think you can be described as energetic.",
"They think that you tend to be remarkably forgiving.",
"They think you are very moralistic. Keep that in mind when you make decisions.",
"They find you very humorous.",
"They think that you are pretty trusting. Be careful who you trust without changing yourself.",
"They know that you are ascetic.",
"They think that you are pretty elegant.",
"They know that you are charismatic.",
"They think that you are pretty possessive over the people you love but that's okay in small doses.",
"They find you very loyal.",
"They think that you tend to be glamorous.",
"They think you can be undisciplined about certain habits and you know it. Try to fix those and things will flow.",
"They find you very an unpolished gem.",
"They think that you tend to be intuitive.",
"They think that you are pretty complex. I admire you.",
"They think you can be dry humored sometimes.",
"They think that you tend to be remarkably creative.",
"They think that you tend to be remarkably logical.",
"They think you can be colorful.",
"They think you can be described as clever.",
"They think you can be delightful.",
"They think that you are quite curious.",
"They know that you are admirable.",
"They think you can be modern.",
"They think you can be so thoughtful and know that your friends appreciate that very much.",
"They think that you are pretty humorous.",
"They know that you are appreciative.",
"They find you very unrestrained. You live your life freely.",
"They think that you tend to be remarkably humble.",
"They think that you are pretty cheerful.",
"They think you are very glamorous.",
"They think that you are pretty unpredictable in others' eyes. People find that intriguing about you.",
"They find you very persuasive.",
"They think that you are quite sophisticated.",
"They know that you are unaggressive. Always stay that way.",
"They find you very sensitive.",
"They think that you tend to be eloquent.",
"They think that you are pretty humorous.",
"They think that you tend to be remarkably iconoclastic.",
"They think that you are pretty humorous.",
"They think that you tend to be observant.",
"They think you can be impulsive. Think better before you make decisions and your life will change dramatically.",
"They think you are very maternal.",
"They find you very rigid about the things you don't like in a person. Maybe if you let go of some of these you could see a different side to people.",
"They think that you tend to be enthusiastic.",
"They think you can be described as charismatic.",
"They think that you are pretty earthy.",
"They think that you are quite eloquent.",
"They think that you are quite mature.",
"They think that you tend to be impressionable.",
"They think that you are quite conscientious.",
"They think you are very charming.",
"They think that you are pretty sophisticated.",
"They think that you are quite persuasive.",
"They think that you tend to be impassive.",
"They think that you tend to be exciting.",
"They think that you are quite an unpolished gem.",
"They think that you tend to be remarkably objective.",
"They think that you are quite admirable.",
"They think you can be described as hearty.",
"They think you can be realistic.",
"They think you are very esthetic.",
"They know that you are spontaneous.",
"They think that you are quite objective.",
"They think that you tend to be remarkably reflective.",
"They think you can be described as energetic.",
"They think that you are quite undisciplined about certain habits and you know it. Try to fix those and things will flow.",
"They think you are very charismatic.",
"They think you are very open.",
"They think that you are pretty brilliant.",
"They think that you are quite personable.",
"They think you can be described as unrestrained. You live your life freely.",
"They think you can be persuasive.",
"They think that you are quite captivating.",
"They think you can be described as protective.",
"They think that you tend to be remarkably ascetic.",
"They think you can be described as delightful.",
"They think that you are quite humble.",
"They think that you tend to be remarkably guileless.",
"They think that you are pretty perceptive.",
"They think that you are quite many-sided.",
"They think that you tend to be big-thinking.",
"They find you very huried.",
"They think you are very elegant.",
"They think you can be described as stubborn. Any problem you have eventually gets resolved.",
"They think that you tend to be winning.",
"They think you are very sociable.",
"They think that you are quite modern.",
"They think that you are pretty clean.",
"They think that you are pretty wishful.",
"They think that you are quite whimsical, people around you think you are a delight.",
"They know that you are frugal.",
"They think that you are quite glamorous.",
"They know that you are confident.",
"They think you can be reflective.",
"They think you can be objective.",
"They think that you tend to be remarkably stubborn. Any problem you have eventually gets resolved.",
"They think you are very wishful.",
"They think that you tend to be steady.",
"They know that you are reliable.",
"They think that you are quite appreciative.",
"They think you can be admirable.",
"They think that you tend to be glamorous.",
"They think that you tend to be dedicated.",
"They think you can be described as huried.",
"They think you are very sociable.",
"They think that you are pretty enigmatic.",
"They think that you are pretty realistic.",
"They think you are very big-thinking.",
"They think that you tend to be remarkably charming.",
"They think that you tend to be remarkably unimaginative sometimes but you have it in you to dream bigger.",
"They think you can be trusting. Be careful who you trust without changing yourself.",
"They think you can be described as intuitive.",
"They think that you are pretty competitive. It helps you get ahead.",
"They think that you are pretty rational.",
"They think that you are quite ascetic.",
"They think that you are quite appreciative.",
"They think that you are quite loyal.",
"They think that you tend to be loyal.",
"They think you can be described as exciting.",
"They think you are very methodical.",
"They think you can be perceptive.",
"They think you can be described as high-spirited.",
"They think that you tend to be remarkably too transparent sometimes. Keep in mind white lies don't hurt.",
"They find you very curious.",
"They think that you tend to be remarkably trusting. Be careful who you trust without changing yourself.",
"They think that you are quite observant.",
"They find you very unpredictable in others' eyes. People find that intriguing about you.",
"They think that you are quite eloquent.",
"They find you very methodical.",
"They find you very too transparent sometimes. Keep in mind white lies don't hurt.",
"They think that you are quite imaginative.",
"They find you very colorful.",
"They think that you tend to be remarkably wishful.",
"They think that you tend to be charismatic.",
"They think you are very sociable.",
"They think you can be described as sociable.",
"They think that you tend to be remarkably patient.",
"They think that you are quite innovative.",
"They think that you tend to be unimaginative sometimes but you have it in you to dream bigger.",
"They think that you tend to be high-spirited.",
"They think you are very impressive.",
"They think you can be freethinking.",
"They think that you are quite forgiving.",
"They know that you are reflective.",
"They think you are very peaceful.",
"They think that you are quite conscientious.",
"They think you can be strong.",
"They think you can be glamorous.",
"They find you very humorous.",
"They think that you tend to be empathetic.",
"They find you very hypnotic.",
"They think you can be idealistic.",
"They find you very independent.",
"They think you are very hypnotic.",
"They find you very peaceful.",
"They think you are very optimistic.",
"They think that you are pretty undisciplined about certain habits and you know it. Try to fix those and things will flow.",
"They know that you are formal.",
"They think you can be moralistic. Keep that in mind when you make decisions.",
"They think that you are pretty determined. Never give up on what you love.",
"They think that you are pretty objective.",
"They think you can be honest.",
"They think you are very appreciative.",
"They find you very delightful.",
"They know that you are forgetful. Just take more notes of things that matter.",
"They think that you are pretty innovative.",
"They think that you tend to be ascetic.",
"They think that you are quite an unpolished gem.",
"They think that you are pretty winning.",
"They find you very creative.",
"They think that you are quite hearty.",
"They think you can be described as hypnotic.",
"They think that you are quite compassionate.",
"They think you can be described as freethinking.",
"They think that you tend to be remarkably naive. But that makes you you.",
"They think you can be described as unpredictable in others' eyes. People find that intriguing about you.",
"They think you are very open.",
"They think that you are quite complex. I admire you.",
"They think that you are quite whimsical, people around you think you are a delight.",
"They think that you are pretty tense about a relationship in your life but trust me there's nothing to worry.",
"They find you very impressionable.",
"They think that you tend to be remarkably folksy.",
"They think that you are pretty strong.",
"They find you very rigid about the things you don't like in a person. Maybe if you let go of some of these you could see a different side to people.",
"They think you can be objective.",
"They think you can be described as shy.",
"They think you can be described as frugal.",
"They think that you are pretty folksy.",
"They know that you are complex. I admire you.",
"They think that you are quite charming.",
"They think that you tend to be folksy.",
"They think that you are pretty maternal.",
"They know that you are mature.",
"They think you are very lovable. People love to be around you.",
"They think you are very unrestrained. You live your life freely.",
"They think that you are quite personable.",
"They think you can be maternal.",
"They think you are very objective.",
"They think that you are pretty colorful.",
"They think that you are pretty big-thinking.",
"They think you are very imaginative.",
"They think that you tend to be impressionable.",
"They think that you are quite appreciative.",
"They think that you tend to be guileless.",
"They think that you tend to be remarkably idiosyncratic.",
"They think that you are quite clean.",
"They think that you tend to be vulnerable to ill-meaning people because you tend to be too trusting sometimes. Trust with caution.",
"They think you are very irreverent.",
"They think that you are pretty impressionable.",
"They think that you tend to be reflective.",
"They think you are very reflective.",
"They think that you are pretty stable.",
"They think that you are quite unpredictable in others' eyes. People find that intriguing about you.",
"They know that you are loyal.",
"They think that you tend to be remarkably unimaginative sometimes but you have it in you to dream bigger.",
"They think you can be idiosyncratic.",
"They know that you are protective.",
"They think you can be charismatic.",
"They think that you are pretty rational.",
"They know that you are idealistic.",
"They know that you are sensitive.",
"They know that you are unimaginative sometimes but you have it in you to dream bigger.",
"They think you can be reflective.",
"They know that you are creative.",
"They know that you are maternal.",
"They think you are very winning.",
"They find you very wise even if you don't know it. Your take on things is insightful.",
"They think you can be described as well-rounded.",
"They find you very earthy.",
"They find you very determined. Never give up on what you love.",
"They think that you tend to be hypnotic.",
"They think that you tend to be remarkably clean.",
"They think that you tend to be remarkably hypnotic.",
"They think that you tend to be confident.",
"They think you are very shy.",
"They think that you are pretty sophisticated.",
"They think that you tend to be mature.",
"They think that you tend to be high-spirited.",
"They think that you tend to be ascetic.",
"They find you very eloquent.",
"They find you very freethinking.",
"They think you can be undisciplined about certain habits and you know it. Try to fix those and things will flow.",
"They think you are very warm.",
"They know that you are undisciplined about certain habits and you know it. Try to fix those and things will flow.",
"They think you are very reflective.",
"They think that you tend to be curious.",
"They think you are very open.",
"They think that you tend to be humble.",
"They think that you are quite irreverent.",
"They find you very many-sided.",
"They think that you are pretty warm.",
"They think that you are quite sympathetic.",
"They think that you tend to be remarkably creative.",
"They find you very elegant.",
"They think that you tend to be remarkably intuitive.",
"They know that you are vulnerable to ill-meaning people because you tend to be too trusting sometimes. Trust with caution.",
"They think that you are pretty iconoclastic.",
"They think you can be cerebral. People around you admire your intelligence.",
"They know that you are freethinking.",
"They find you very rigid about the things you don't like in a person. Maybe if you let go of some of these you could see a different side to people.",
"They think that you tend to be energetic.",
"They think that you tend to be helpful.",
"They think that you tend to be remarkably insightful.",
"They think that you tend to be reliable and gentle. Your friends find you comforting.",
"They think that you tend to be remarkably passionate.",
"They think you can be sympathetic.",
"They know that you are empathetic.",
"They think you are very skillful.",
"They think that you are pretty charismatic.",
"They think that you are quite independent.",
"They think that you are pretty forgiving.",
"They think that you tend to be remarkably imaginative.",
"They know that you are passionate.",
"They think that you are pretty skillful.",
"They think that you are pretty tough. You can break through any problem.",
"They find you very reliable.",
"They know that you are extraordinary.",
"They think that you tend to be cerebral. People around you admire your intelligence.",
"They think you can be described as stubborn. Any problem you have eventually gets resolved.",
"They find you very unaggressive. Always stay that way.",
"They think that you are pretty possessive over the people you love but that's okay in small doses.",
"They think that you tend to be remarkably sensitive.",
"They think you are very passionate.",
"They think that you tend to be remarkably innovative.",
"They know that you are unrealistic about the dreams of the people you love.",
"They think you can be described as winning.",
"They think you are very unrealistic about the dreams of the people you love.",
"They think that you are pretty optimistic.",
"They think that you are pretty methodical.",
"They think you can be described as high-spirited.",
"They think you can be observant.",
"They think you can be impressive.",
"They think that you are pretty a trend setter but you don't know it. be careful who you influence around you.",
"They find you very graceful. Your friends admire you.",
"They think that you are pretty unrestrained. You live your life freely.",
"They think you are very dedicated.",
"They find you very creative.",
"They know that you are impassive.",
"They think that you tend to be remarkably patient.",
"They think you can be described as tolerant but hyper-reactive sometimes. Think before you do something and you will get what you want.",
"They think that you tend to be well-rounded.",
"They find you very respectful.",
"They think that you tend to be glamorous.",
"They think that you tend to be mellow.",
"They think that you are quite humorous.",
"They think you can be described as ambitious.",
"They think that you are pretty cheerful.",
"They think that you tend to be iconoclastic.",
"They find you very sympathetic.",
"They think that you are quite sensitive.",
"They think you are very sympathetic.",
"They think that you are pretty open.",
"They think that you are pretty moralistic. Keep that in mind when you make decisions.",
"They find you very winning.",
"They think you can be dry humored sometimes.",
"They think that you are quite cerebral. People around you admire your intelligence.",
"They think that you tend to be intense.",
"They think that you tend to be remarkably admirable.",
"They think that you are pretty considerate.",
"They think that you tend to be high-spirited.",
"They think that you tend to be remarkably a trend setter but you don't know it. be careful who you influence around you.",
"They think that you are pretty vulnerable to ill-meaning people because you tend to be too trusting sometimes. Trust with caution.",
"They know that you are graceful. Your friends admire you.",
"They think that you are pretty personable.",
"They think that you tend to be remarkably honest.",
"They think that you tend to be individualistic.",
"They think you are very passionate.",
"They find you very cerebral. People around you admire your intelligence.",
"They think you can be described as eloquent.",
"They think that you are pretty earthy.",
"They find you very unpredictable in others' eyes. People find that intriguing about you.",
"They think that you are pretty impressionable.",
"They think that you tend to be remarkably frugal.",
"They think you are very enthusiastic.",
"They think that you are pretty formal.",
"They think you can be observant.",
"They think that you are pretty appreciative.",
"They think that you are pretty friendly.",
"They think you can be described as enigmatic.",
"They think that you tend to be remarkably perceptive.",
"They think that you are pretty rigid about the things you don't like in a person. Maybe if you let go of some of these you could see a different side to people.",
"They think you can be mature.",
"They think that you tend to be remarkably caring.",
"They think that you are quite dry humored sometimes.",
"They think you are very intense.",
"They think you can be described as honest.",
"They find you very whimsical, people around you think you are a delight.",
"They think that you are pretty tense about a relationship in your life but trust me there's nothing to worry.",
"They know that you are conscientious.",
"They think you can be described as helpful.",
"They think that you tend to be remarkably humble.",
"They think that you are quite insightful.",
"They know that you are self-reliant.",
"They think that you are quite folksy.",
"They think you can be described as steady.",
"They know that you are iconoclastic.",
"They think that you are pretty family-oriented.",
"They think that you are quite methodical.",
"They think that you are quite guileless.",
"They find you very colorful.",
"They think you can be described as emotional.",
"They think you can be folksy.",
"They think you can be esthetic.",
"They know that you are enigmatic.",
"They think you can be described as vulnerable to ill-meaning people because you tend to be too trusting sometimes. Trust with caution.",
"They know that you are enigmatic.",
"They find you very considerate.",
"They think that you are pretty skillful.",
"They think that you are pretty enigmatic.",
"They think you can be described as tolerant but hyper-reactive sometimes. Think before you do something and you will get what you want.",
"They think that you tend to be charming.",
"They think that you tend to be remarkably unaggressive. Always stay that way.",
"They find you very elegant.",
"They think you can be idiosyncratic.",
"They think that you tend to be remarkably optimistic.",
"They think you can be described as undisciplined about certain habits and you know it. Try to fix those and things will flow.",
"They think you can be described as patient.",
"They think that you are quite glamorous.",
"They think that you are quite naive. But that makes you you.",
"They think you can be creative.",
"They think that you tend to be remarkably reliable.",
"They think that you are quite appreciative.",
"They think that you tend to be remarkably undisciplined about certain habits and you know it. Try to fix those and things will flow.",
"They think that you tend to be remarkably reflective.",
"They think you can be described as independent.",
"They think that you tend to be remarkably perceptive.",
"They think you are very dreamy, but it's good. Keep dreaming they will come true.",
"They know that you are modern.",
"They think that you tend to be remarkably competitive. It helps you get ahead.",
"They find you very mellow.",
"They think that you are pretty well-rounded.",
"They think you are very confident.",
"They find you very compassionate.",
"They think that you tend to be remarkably so thoughtful and know that your friends appreciate that very much.",
"They think that you are quite unaggressive. Always stay that way.",
"They think you can be skillful.",
"They think you can be described as persuasive.",
"They think that you tend to be stubborn. Any problem you have eventually gets resolved.",
"They think that you are quite compassionate.",
"They think you are very dreamy, but it's good. Keep dreaming they will come true.",
"They think that you tend to be remarkably humble.",
"They think that you tend to be remarkably delightful.",
"They find you very shy.",
"They think you can be dry humored sometimes.",
"They think that you are pretty peaceful.",
"They think that you are quite loyal.",
"They think that you tend to be remarkably freewheeling.",
"They know that you are curious.",
"They think you can be described as ambitious.",
"They think that you are pretty compassionate.",
"They think that you tend to be personable.",
"They think that you are quite self-sufficient.",
"They think that you tend to be remarkably intense.",
"They think that you tend to be wise even if you don't know it. Your take on things is insightful.",
"They think that you tend to be appreciative.",
"They think you can be unrestrained. You live your life freely.",
"They think you are very exciting.",
"They think you can be described as protective.",
"They find you very conscientious.",
"They think you are very eloquent.",
"They know that you are caring.",
"They think you can be described as moralistic. Keep that in mind when you make decisions.",
"They think that you tend to be remarkably hardworking.",
"They think you are very conscientious.",
"They think that you are quite strong.",
"They think you can be described as a trend setter but you don't know it. be careful who you influence around you.",
"They find you very energetic.",
"They think that you tend to be remarkably cerebral. People around you admire your intelligence.",
"They think that you tend to be shy.",
"They think that you are pretty cerebral. People around you admire your intelligence.",
"They think that you are quite helpful.",
"They think that you are pretty maternal.",
"They think you are very daring.",
"They think that you tend to be sophisticated.",
"They think that you are pretty sociable.",
"They think you can be described as many-sided.",
"They find you very confident.",
"They think you can be tense about a relationship in your life but trust me there's nothing to worry.",
"They think you are very dedicated.",
"They know that you are personable.",
"They think that you tend to be remarkably many-sided.",
"They know that you are loyal.",
"They think that you are pretty many-sided.",
"They think that you tend to be remarkably idiosyncratic.",
"They know that you are clean.",
"They think you are very forgiving.",
"They think that you tend to be whimsical, people around you think you are a delight.",
"They think that you are pretty observant.",
"They think you can be folksy.",
"They know that you are conscientious.",
"They think you are very honest.",
"They think that you are pretty loyal.",
"They think you are very self-sufficient.",
"They know that you are competitive. It helps you get ahead.",
"They think you are very enthusiastic.",
"They think that you tend to be brilliant.",
"They think you can be described as impressive.",
"They think you are very modern.",
"They find you very stable.",
"They think you can be intense.",
"They think that you are quite many-sided.",
"They think you can be described as dry humored sometimes.",
"They think you can be skillful.",
"They think you can be intelligent.",
"They know that you are creative.",
"They think that you tend to be wise even if you don't know it. Your take on things is insightful.",
"They know that you are complex. I admire you.",
"They think you can be wishful.",
"They think you are very empathetic.",
"They find you very sociable.",
"They find you very freewheeling.",
"They think you are very impatient. But patience is the best virtue.",
"They think you can be described as stable.",
"They think that you are pretty insightful.",
"They think that you are quite self-sufficient.",
"They find you very stable.",
"They think that you are pretty helpful.",
"They find you very winning.",
"They find you very esthetic.",
"They think you can be described as friendly.",
"They think that you tend to be remarkably confident.",
"They think that you tend to be remarkably sociable.",
"They think that you are quite formal.",
"They think that you are quite idiosyncratic.",
"They think that you tend to be impatient. But patience is the best virtue.",
"They think that you are quite esthetic.",
"They think you can be hardworking.",
"They think that you tend to be remarkably intelligent.",
"They think that you are quite spontaneous.",
"They know that you are well-rounded.",
"They know that you are humorous.",
"They think that you tend to be appreciative.",
"They think you can be sociable.",
"They think that you are quite sociable.",
"They think that you are quite impressionable.",
"They think you can be described as forgetful. Just take more notes of things that matter.",
"They think that you tend to be remarkably wishful.",
"They think you can be described as whimsical, people around you think you are a delight.",
"They find you very many-sided.",
"They know that you are charismatic.",
"They think you are very so thoughtful and know that your friends appreciate that very much.",
"They think that you are pretty ascetic.",
"They think you are very empathetic.",
"They think that you are pretty delightful.",
"They think that you are pretty warm.",
"They know that you are exciting.",
"They think that you are pretty logical.",
"They think you are very humble.",
"They think that you tend to be irreverent.",
"They find you very winning.",
"They think you can be described as hearty.",
"They think that you are quite realistic.",
"They think you can be described as focused.",
"They think that you are quite insightful.",
"They think that you tend to be sophisticated.",
"They think you are very many-sided.",
"They think that you tend to be hypnotic.",
"They find you very too transparent sometimes. Keep in mind white lies don't hurt.",
"They find you very conscientious.",
"They think you are very honest.",
"They find you very esthetic.",
"They think that you are pretty vulnerable to ill-meaning people because you tend to be too trusting sometimes. Trust with caution.",
"They think you can be determined. Never give up on what you love.",
"They think you can be described as a trend setter but you don't know it. be careful who you influence around you.",
"They think that you are pretty eloquent.",
"They think that you are quite humorous.",
"They think you are very exciting.",
"They find you very lovable. People love to be around you.",
"They think you are very clean.",
"They think you can be personable.",
"They think you can be innovative.",
"They think that you are pretty reliable and gentle. Your friends find you comforting.",
"They think you can be described as dry humored sometimes.",
"They think you are very curious.",
"They think that you tend to be amusing.",
"They think that you are pretty considerate.",
"They find you very passionate.",
"They think you can be independent.",
"They think that you tend to be modern.",
"They think you are very delightful.",
"They think you can be described as naive. But that makes you you.",
"They think you can be creative.",
"They think you can be trusting. Be careful who you trust without changing yourself.",
"They know that you are maternal.",
"They think you are very high-spirited.",
"They think that you tend to be confident.",
"They think that you tend to be remarkably independent.",
"They think you can be described as personable.",
"They find you very an unpolished gem.",
"They think that you tend to be so thoughtful and know that your friends appreciate that very much.",
"They think that you are pretty trusting. Be careful who you trust without changing yourself.",
"They think you can be unimaginative sometimes but you have it in you to dream bigger.",
"They think that you tend to be reflective.",
"They think you can be described as humorous.",
"They think that you tend to be remarkably considerate.",
"They think that you tend to be freethinking.",
"They think you are very intense.",
"They find you very focused.",
"They think you are very an unpolished gem.",
"They think you can be described as stable.",
"They find you very hardworking.",
"They know that you are patient.",
"They think you can be so thoughtful and know that your friends appreciate that very much.",
"They think that you are pretty optimistic.",
"They think that you are quite ascetic.",
"They know that you are trusting. Be careful who you trust without changing yourself.",
"They know that you are resourceful.",
"They think that you tend to be remarkably graceful. Your friends admire you.",
"They think you can be described as insightful.",
"They think you can be idealistic.",
"They think you are very trusting. Be careful who you trust without changing yourself.",
"They know that you are graceful. Your friends admire you.",
"They think you can be fun-loving.",
"They think that you are pretty skillful.",
"They think that you are pretty innovative.",
"They think that you are pretty unpredictable in others' eyes. People find that intriguing about you.",
"They think that you tend to be remarkably admirable.",
"They think you can be big-thinking.",
"They think that you tend to be earthy.",
"They think that you are quite curious.",
"They find you very reflective.",
"They think you are very folksy.",
"They think that you are pretty earthy.",
"They know that you are delightful.",
"They think that you tend to be irreverent.",
"They think that you are quite intense.",
"They think that you tend to be remarkably winning.",
"They think that you tend to be irreverent.",
"They think that you tend to be remarkably realistic.",
"They think that you are pretty tense about a relationship in your life but trust me there's nothing to worry.",
"They think that you are quite individualistic.",
"They think that you tend to be rational.",
"They think you can be described as perceptive.",
"They think that you tend to be remarkably too transparent sometimes. Keep in mind white lies don't hurt.",
"They think that you are pretty graceful. Your friends admire you.",
"They think that you are pretty hardworking.",
"They think that you are quite patient.",
"They find you very unrealistic about the dreams of the people you love.",
"They think that you tend to be remarkably possessive over the people you love but that's okay in small doses.",
"They think that you are quite forgetful. Just take more notes of things that matter.",
"They think that you are quite extraordinary.",
"They find you very sympathetic.",
"They think that you are quite lovable. People love to be around you.",
"They think that you tend to be remarkably intense.",
"They think that you are quite imaginative.",
"They think that you are pretty graceful. Your friends admire you.",
"They find you very frugal.",
"They know that you are unrealistic about the dreams of the people you love.",
"They think that you tend to be conscientious.",
"They think that you are quite helpful.",
"They think that you tend to be sophisticated.",
"They think you can be described as undisciplined about certain habits and you know it. Try to fix those and things will flow."]