export const adviceArray = [ "It seems that you have been pretty tired lately. Just be nice to someone at the grocery store, your day will get better and you will have more energy.",
 "I know that you love to laugh, something very funny is going to happen soon. Share it with people close to you. ",
 "Don't be so caught up on being with someone. You are enough. Once you find happiness within yourself, you will attract the right person.",
 "There's someone that lives near you that adores you. You might be interested in them as well. ",
 "Someone who has brown hair loves you but doesn't even know it themself. If you show them how amazing you are, they might realize how they feel. ",
 "Someone close to you and yourself have been having problems. Give them space and take your own space to grow. It doesn't mean anything bad. Distance makes the heart grow fonder. ",
 "Someone very close to you is planning something that's going to make you smile. ",
 "You have been gaining a couple of bad habits in the last few years. Cut them out of your life and you will feel the weight get lifted.",
 "You need a bloody mary! It's been one hell of a month! ",
 "Next year is going to be the best year of your life. Patience is key.",
 "Don't worry about things you have no control over.",
 "A lot of different paths and options in your life. Whichever path you take will be the correct path.",
 "After you get your daily tarot reading just go outside and breath for a second. Mindfulness will make you feel 100%!",
 "You will have to chose between two things. Make the decision when you're 51% sure It's the correct thing to do. ",
 "Don't dwell in the past, let go. ",
 "Everything happens for a reason. Sometimes the worst things could lead to the best things that will happen. ",
 "Now is the time to do that thing you always dreamt of doing. ",
 "You can lose everything anytime but that's why life is beautiful. The sight is the only thing you have use it wisely, enjoy it. ",
 "Don't fixate too much on the destination, and enjoy the journey. ",
 "Take some time and smell the coffee. you'llll discover that life is great. ",
 "I know you worry easily, but sometimes it is just best to go with the flow. Ultimately, it all ends up working out.",
 "When you're 90 years old, you're gonna look back. You're not going to think 'I wish spent more time on social media or did more work or had a better car', you will say 'I wish I spent more time with the people I love'. You are loved by so many people, go spend time with them.",
 "Someone might have been treating you not the way you deserve these past week. The way someone treats you is a reflection of how they feel about themselves. You should still be nice to them. Eventually they will become better too.",
 "When you know better, do better. You are about to embark on a big decision. Do your research before-hand!",
 "I know you have big goals. Just keep going. No matter what. That's how all successful people succeed. I can see that you will be successful at the end.",
 "I know you go through a lot of stress at times but Don't dwell on the past. No regrets!",
 "You are going to meet someone in either 3 days, weeks or months. Listen more than you speak. They are going to tell you something you need to hear. ",
 "Do what you’re afraid to do. I can tell that your biggest dreams depend on it.",
 "Forgive the person that did you wrong. I know It's hard but it is going to open doors to a better posibility. ",
 "Patience is a virtue.",
 "Watch your step. You will be taking big ones soon.",
 "Your heart, it is in the clear. This signifies future pleasure. ",
 "Find your passion and figure out how to fulfil it. ",
 "You possess admirable qualities; directness, spontaneity and independence.",
 "Remember that patience is a virtue. ",
 "Put your fears behind you and walk your own path. ",
 "Approach your tasks with wisdom and assurance, everything in life is a test of your endurance.",
 "Change your line of work or seek more challenges.",
 "Your future holds an abundance of richness or friendships.",
 "You are struggling with overburdening of work, pressure, commitment or absolute destruction.",
 "You seek the contentment of the heart, you may be getting closer to what you want.",
 "You are a true believer in the perfection of human love.",
 "Concurring danger and reaching safety is on the horizon, soon you will find serenity.",
 "Passage from pain and an end to struggle is near.",
 "Remember a simpler time and get back to basics.",
 "The future holds a union of two people, groups, ideas or entities.",
 "Be yourself and more open to new connections in your life",
 "This is not a good time to separate or stay apart from loved ones.",
 "You have been waiting a long time to forgive or be forgiven. Follow your intuition.",
 "You will soon find reconciliation; with another or within yourself.",
 "If you are reading a book, read it with yearning.",
 "A struggle within yourself or with another, will come to an end and harmony will be restored.",
 "Inner peace is what you seek.",
 "Your feelings about a person or idea have gotten really strong, it might be time to reconsider.",
 "You should take the time to reflect on your tendency to pair-up.",
 "You feel connection to others, a need to bring two entities or forces together.",
 "You can be defensive and unable to give up control. Relax and let nature take its course.",
 "Your weakness is that you are unable to accept loss. Invest time in cultivating resilience and try to adapt to whatever the fates may throw your way.",
 "You will soon achieve self-reliance, autonomy or financial independence.",
 "You are stable and steady, or you seek to be stable and steady.",
 "You seem to be enmeshed in a difficult place; situation, relationship and you are trying to escape.",
 "Reflect on your connections and how they affect your state of mind.",
 "You will find enlightenment in an unlikely place or through an unlikely person.",
 "The journey to the serenity starts within you, the best path is usually not around but through.",
 "This is a good way to remember that you have control over your actions, emotions and thoughts.",
 "You will soon face a challenge that requires strength but not brute force, forget all the distractions and go back to the source.",
 "Do not succumb to temptation for you may be standing in the way of your own personal growth and self-actualization.",
 "Act on your instincts. Accept help if you need it or provide support to a loved one in need.",
 "A new source of money, work, or an opportunity to improve your financial situation will be made available to you if you're patient.",
 "You will soon have to make a very important decision, do not look to the past for a solution. ",
 "You are a seeker, a skeptic and/or an adventurer.",
 "You are guarded with your emotions and thoughts because of some events that have taken place in the past. ",
 "Your partner, friend or lover want the same thing that you do. If you care to listen, do not be dismissive and stubborn.",
 "You are about to embark on a fecund time of productivity, creativity, great results or mastery.",
 "Rely on your community to achieve your emotional goals. Try to cultivate genuine connections.",
 "This is a time to look around and lend a helping hand.",
 "You are about to uncover an inner passion or an opportunity to be a nurturing person",
 " There is a decisive person in your circle, lean on them for support for the next hurdle.",
 "Use reason or eloquent speech to remove confusion and reveal what the truth could be.",
 "You are spiritual and you seek enlightenment; and/or inspiration from a moral advisor.",
 "You are sensitive and you have a huge imagination. You do not like the mundane.",
 "Start a creative or entrepreneurial project, seek information or go on a trek.",
 "You seek stability and completion, peace and harmony.",
 "Embrace new beginnings; opportunities or incentives.",
 "Positivity, good results and/ or perfected work are in your future.",
 "You may be asked to answer for your deeds.",
 "If you continue on your current path, you may miss out on an opportunity for growth.",
 "You are longing for experience, knowledge and substance.",
 "You may be acting impetuously; because your worldview is skewed.",
 "Fight bravely for what you believe in; even if you feel foolish during.",
 "You are action-oriented, opinionated and at times you act in haste.",
 "You are a free thinker with an unusual clarity of mind and you have the right balance of skepticism and wisdom.",
 "Trust your instincts and practice self-protection, proceed with caution.",
 "A new source of inspiration will enter your life, stay open to new ideas or a new enterprise.",
 "Remember that it is darkest before dawn.",
 "Whatever is happening now is a test of faith and you must be resilient, it is easy to give up but you shouldn't.",
 "Remind yourself that everything is an opportunity for growth and gaining maturity.",
 "Take the path of least resistance.",
 "You are a secret optimist who cannot be discouraged.",
 "Place trust in your present feelings.",
 "This is the time for recuperation, rest and relaxation.",
 "Be on the lookout for a turning point, a new development, new possibilities or an expansion.",
 "Do not be frazzled by a sudden change, an uncomfortable experience, a blow to the ego or an unimaginable transformation.",
 "You have all the necessary qualities to conquer your fears; you're self-reliant, confident and persevering.",
 "Ease into the transition into a new state. There is no point in resisting.",
 " The is an ending, a conclusion or a loss in your near future.",
 "Rely on your survival instincts, your good sense and your ability to react in this next phase. You have been preparing for this in many ways.",
 "In order to find what you're looking for, try to become more aware of where you are.",
 "The past weighs you down, let it go.",
 "In the coming months you will strive and make advances in the most important project yet.",
 "You are striving to maintain a position or a possesssion.",
 "Soon your courage and tenacity will be tested, this will determine your long-term success.",
 "Your current phase of hardship is coming to an end, and you will enjoy triumph and reward.",
 "Your desires and lapses in impulse control may be getting the best of you.",
 "You are yearning for a more innocent time.",
 "You are kind-hearted, benevolent and show a lot of mercy. Remember to spare this for those who are worthy.",
 "Many rely on you to make the right choice, so focus and try your best.",
 "Keep your ears open for new and valuable information. This is not the time for doubt or hesitation.",
 "A new creative beginning is approaching.",
 "You are a dreamer; perceptive, emotionally sensitive and intuitive. ",
 "You are down-to-earth, grounded and self-aware.",
 "Be careful of temptation, self-delusion and wishful thinking.",
 "You will be presented with potential solutions. If you choose wisely, you will gain redemption.",
 "A force or renewal, rejuvenation and change will come to your life in the form of a dilemma. ",
 "Do not let despair and bereavement get a hold of you, try to find serenity in your relationships and the people who care for you.",
 "You will have to draw on lessons learned from a past failure soon, introspection is an important tool.",
 "You Don't believe in mystical vision, but soon you will learn its value.",
 "The price of wisdom is struggle, remember that the next time you face trouble.",
 "Pay attention to what is lurking in your subconscious mind, these thoughts may be keeping you confined.",
 "You have been tired lately. Just be nice to someone at the grocery store. Your day will get better and inevidently you willl have more energy.",
 "I know that you love to laugh. Something very funny is going to happen soon. Share it with people close to you. ",
 "Don't be so caught up on being with someone. You are enough. Once you find happiness within yourself, you will attract the right person.",
 "There's someone who lives near you that adores you. You might be interested in them as well. ",
 "You and someone you care about have been having problems. Just give them space and take your own space to grow. It doesn't mean anything bad. Distance makes the heart grow fonder. ",
 "Someone very close to you is planning something that's going to make you smile. ",
 "You have been gaining a couple of bad habits in the last few years. Cut them out of your life and feel the weight lifted.",
 "You need a bloody marry! It's been a hell of a month! ",
 "Next year is going to be the best year of your life. Patience is key.",
 "Don't worry about things you have no control over.",
 "There are a lot of different paths and options in your life. Whichever path you take will be the correct path.",
 "After you get your daily tarot reading just go outside and breath for a second. Mindfulness will make you feel 100%!",
 "You will have to choose between two things. Make the decision when you're 51% sure It's the correct thing to do. ",
 "Don't dwell in the past, let go. ",
 "Everything happens for a reason. Sometimes the worst things could lead to the best things that will happen. ",
 "Now is the time to do that thing you always dreamt of doing. ",
 "You can lose everything anytime but that's why life is beautiful. The insight is the only thing you have, use it wisely. ",
 "Don't fixate too much on the destination, and enjoy the journey. ",
 "Take some time and smell the coffee. you'llll discover that life is great. ",
 "I know you worry but think about it. No matter what happens in a scope of a couple years if It's not important it probably wasn't to begin with. ",
 "When you're 90 years old, you're gonna look back. You're not going to think 'I wish I spent more time on social media or did more work or had a better car', you will say 'I wish I spent more time with the people I love'. You are loved by so many people, go spend time with them.",
 "Don't worry, you are a very lucky person and no matter what you will always be protected from evil.",
 "Don't forget you are the only one who can control your future. Choose wisely.",
 "Don't forget your choices matter, make sure to base them on many different perspectives.",
 "Don't forget people you love are the most valuable assets you have. Be careful who you let in your life. Show appreciation to ones who deserve it. ",
 "Don't forget you only live once! Enjoy life.",
 "Don't forget anything can be an opportunity  if you look at it from the right angle. Be open to shifting your perspective.",
 "Don't forget you have control over how you experience life. You can choose to see the bright side.",
 "The cup is not half empty this time. It's mostly full. Things will eventually make you very happy. ",
 "Take  necessary precautions rather than waiting till the last minute. It is better to prevent than to cure.",
 "you're great at giving advice, not so much at following it. Follow your own advice and everything will end up amazing.",
 "Remember, keep an open mind. Life is full of surprises.",
 "Remember, live life to the fullest because you may not have it tomorrow.",
 "My advice is never bet your money on another person's game. You know yourself and you should trust yourself when in need.",
 "you'llll have to make an important decision soon. Put on your thinking cap. be thoughtful before you decide.",
 "Two wrongs Don't make a right. When someone has done something bad to you, trying to get revenge will only make things worse.",
 "The pen is mightier than the sword. Trying to convince people with ideas and words is more effective than trying to force people to do what you want.",
 "When in Rome, do as the Romans. Act the way that the people around you are acting. This phrase might come in handy when you're traveling abroad-notice that people do things differently than you're used to.",
 "The squeaky wheel gets the grease. You can get better service if you complain about something. If you wait patiently, no one's going to help you.",
 "When the going gets tough, the tough get going. Strong people Don't give up when they come across challenges. They just work harder.",
 "No man is an island. You can't live completely independently. Everyone needs help from other people",
 "Fortune favors the bold. People who bravely go after what they want are more successful than people who try to live safely.",
 "People who live in glass houses should not throw stones. Don't criticize other people if you're not perfect yourself.",
 "Hope for the best, but prepare for the worst. Bad things might happen, so be prepared.",
 "Better late than never. It's best to do something on time. But if you can't do it on time, do it late.",
 "Birds of a feather flock together. People like to spend time with others who are similar to them.",
 "Keep your friends close and your enemies closer. If you have an enemy, pretend to be friends with them instead of openly fighting with them. That way you can watch them carefully and figure out what they're planning.",
 "A picture is worth a thousand words. Pictures convey emotions and messages better than written or spoken explanations.",
 "There's no such thing as a free lunch. Things that are offered for free always have a hidden cost.",
 "There's no place like home. Your own home is the most comfortable place to be.",
 "Discretion is the greater part of valor. Sometimes It's important to know when to give up and run away, instead of always acting brave and maybe getting hurt.",
 "The early bird catches the worm. You should wake up and start work early if you want to succeed.",
 "Never look a gift horse in the mouth. If someone offers you a gift, Don't question it.",
 "You can't make an omelet without breaking a few eggs. When you try to do something great, you'llll probably make a few people annoyed or angry. Don't worry about those people; just focus on the good results.",
 "God helps those who help themselves. Don't just wait for good things to happen to you. Work hard to achieve your goals.",
 "You can't always get what you want. Don't whine and complain if you Don't get what you wanted.",
 "Cleanliness is next to godliness. Be clean. God likes that.",
 "A watched pot never boils. If something takes time to finish, Don't watch it too closely because it will seem like It's taking forever.",
 "Beggars can't be choosers. If you're asking for a favor from someone else, you have to take whatever they give you.",
 "Actions speak louder than words. Just saying that you'llll do something doesn't mean much. Actually doing it is harder and more meaningful.",
 "If it ain't broke, Don't fix it. Don't try to improve something that already works fairly well. you'llll probably end up causing new problems.",
 "Practice makes perfect. You have to practice a skill a lot to become good at it.",
 "Too many cooks spoil the broth. When there are too many people trying to lead and give their opinions, It's confusing and leads to bad results. Jobs and projects should have one or two strong leaders.",
 "Easy come, easy go. When you get money quickly, like by winning it, It's easy to spend it or lose it quickly as well.",
 "Don't bite the hand that feeds you. If someone's paying you or helping you out, you have to be careful not to make them angry or say bad things about them.",
 "All good things must come to an end. You can't keep having good luck or fun forever; eventually it will stop.",
 "If you can't beat em, join em. When you try to change someone's behavior and it doesn't work, you might have to change instead. For example, if you're trying to get your classmates to focus on studying but they want to party, maybe you should just party with them.",
 "One man's trash is another man's treasure. Different people have different ideas about what's valuable.",
 "There's no time like the present. If you need to do something, Don't wait until later. Do it now.",
 "Beauty is in the eye of the beholder. Different people have different ideas about what's beautiful.",
 "Necessity is the mother of invention. When you're really in need, you think of creative solutions to your problems.",
 "A penny saved is a penny earned. Save your money. Saving money is just like making money.",
 "Familiarity breeds contempt. When you're around someone for too long, you get tired of them and annoyed by them.",
 "You can't judge a book by its cover. Things sometimes look different than they really are. A restaurant that looks old and small might have amazing food, for example.",
 "Good things come to those who wait. Be patient. Eventually something good will happen to you.",
 "Don't put all your eggs in one basket. Have a backup plan. Don't risk all of your money or time in one plan.",
 "Two heads are better than one. When two people cooperate with each other, they come up with better ideas.",
 "The grass is always greener on the other side of the hill. People tend to want whatever they Don't have.",
 "Do unto others as you would have them do unto you. Don't do mean things to people.",
 "A chain is only as strong as its weakest link. If one member of a team doesn't perform well, the whole team will fail.",
 "Honesty is the best policy. Don't lie.",
 "Absence makes the heart grow fonder. Sometimes It's good way to be away from your partner, because it makes you want to see each other again.",
 "You can lead a horse to water, but you can't make him drink. If you try to help someone, but they Don't take your advice or offers, give up. You can't force someone to accept your help.",
 "Don't count your chickens before they hatch. Your plans might not work out, so Don't start thinking about what you'llll do after you succeed. Wait until you'llve already succeeded, and then you can think about what to do next.",
 "If you want something done right, you have to do it yourself. Don't trust other people to do important things for you. You have to do things yourself to control the quality of the results.",
 "A broken clock is right twice a day. When an old clock stops working, it shows one specific time but doesn't move. So once in the day and once at night, the clock is pointing to the correct time. In the same way, even a person who's not very smart can sometimes be correct by accident.",
 "A friend in need is a friend indeed. If someone helps you when you're in trouble, that person is a true friend.",
 "A little bit of knowledge is a dangerous thing. Sometimes when a person knows a little bit about something, they feel like they're an expert. Because they feel like an expert, they try to do things that they shouldn't and they mess everything up.",
 "A journey of a thousand miles begins with a single step. Some things, like learning to speak English fluently, take a really long time. It might seem like too much work. But the only way to achieve your goals is to start working now.",
 "All is fair in love and war. In love and romance, you sometimes do things that aren't very nice. For example, you might break up with someone or steal another person's partner. This phrase means that that's OK.",
 "All work and no play makes Jack a dull boy. You can't work all of the time. You have to relax as well.",
 "Better safe than sorry. You should be careful, even if it seems like It's not necessary. The consequences if something goes wrong are much worse than wasting a little time and effort by being careful.",
 "Better the devil you know than the one you Don't. When you have a choice between two bad things, It's safer to pick the bad thing that you'llve already experienced. The other bad thing might be worse.",
 "Don't judge a man until you have walked a mile in his shoes. Sometimes people criticize each other. But It's not fair to criticize someone else if you haven't had the same experiences.",
 "Don't put the cart before the horse. Pay attention to what's most important. Don't let things which aren't as important take up all of your time and attention.",
 "Don't talk the talk if you can't walk the walk. You shouldnt brag about being able to do something if you can't actually do it.",
 "Don't throw out the baby with the bath water. When you're trying to get rid of something bad, you might accidentally get rid of the good things that are connected with it as well. Don't do that.",
 "Early to bed and early to rise makes a man healthy, wealthy and wise. It means It's healthy and smart to go to sleep early and wake up early.",
 "Every cloud has a silver lining. When something bad happens to you, Don't get too upset. There's usually something good associated with any bad experience. For example, if you get fired from your job, it might push you to get a better job instead.",
 "Give a man a fish, he eats for a day. Teach a man how to fish, he eats for a lifetime. Don't try to help people by just giving them things. The result will be temporary. If you want to help someone long-term, teach them how to do things on their own.",
 "Great minds think alike. Smart people often have the same ideas. Say this when someone has the same smart idea that you have."]