export const thanksArray = ["Family",
 "Health",
 "Friends",
 "Education",
 "Food",
 "Song",
 "Shower",
 "Internet",
 "Job",
 "Dream",
 "Sunrise",
 "Eyesight",
 "Home",
 "Holiday",
 "Pets",
 "Surprises",
 "Kindness",
 "Rainbows",
 "Good Meal",
 "Good News",
 "Chocolate",
 "New Day",
 "Freedom",
 "Doctors",
 "Cups of tea",
 "Cuddles",
 "Walks",
 "Memories",
 "Snoozing alarm",
 "Discoveries",
 "Travelling",
 "Date nights",
 "Movies",
 "Winning",
 "Dancing",
 "Fresh water",
 "Uncontrollable laughter",
 "Living pain-free",
 "Goodnight kisses",
 "Imagination",
 "Love",
 "Sleep",
 "Nature",
 "Coffee",
 "Technology",
 "Electricity",
 "Smiles",
 "Achieving Goals",
 "Good hair days",
 "Unconditional Love",
 "Sales",
 "Waking up ",
 "Advancements",
 "Me time",
 "Kindness",
 "Uniqueness",
 "Mistakes",
 "The weekend",
 "Payday",
 "The seasons",
 "Human rights",
 "Colors",
 "Choices",
 "Co-workers",
 "Puppies",
 "Equality and diversity",
 "Traditions",
 "Nice neighbors",
 "Honesty",
 "Future ",
 "Deep conversations",
 "Forgiveness",
 "Teamwork",
 "Spell checker",
 "Swimming ",
 "Music",
 "Comfortable clothes",
 "Who you are",
 "Senses",
 "Good habits",
 "Emotions",
 "Dreaming",
 "Comminication",
 "Fresh bed sheets ",
 "Vacations",
 "Long drives",
 "Having a passion",
 "Transportation",
 "Old photographs",
 "Old friends",
 "Snow days",
 "Bubble bath",
 "Mornings",
 "Sunday mornings",
 "Bad days",
 "Helping others",
 "Sincere apologies",
 "Open minds",
 "Strength",
 "Generosity",
 "Respect",
 "Sunset",
 "Sky",
 "Breathing",
 "Water",
 "Ocean",
 "Running",
 "Holidays",
 "Children",
 "The sun",
 "The planets",
 "The earth",
 "Phone calls",
 "Texts",
 "Blue",
 "Green",
 "Red",
 "Fortunes",
 "Horoscopes"]