

default_platform(:ios)

platform :ios do
  desc "Sinc Signing"
  lane :signing do

  end

  desc "BUILD"
  lane :build do
    signing

  end

  desc "UPLOAD TO TESTFLIGHT"
  lane :beta do
    build
    increment_build_number(xcodeproj: "FortuneCoffee.xcodeproj")
    build_app(workspace: "FortuneCoffee.xcworkspace", scheme: "FortuneCoffee")
    upload_to_testflight
  end


end
