export const compatibilityArray = {
    Virgo: {
        Aries: ['Surprise Vacation', 'Bar Crawl', 'Make time for them', 'Complements', 'Low', 'Low', 'High'],
        Aquarius: ['Watch', 'bed and breakfast', 'WRITE A LOVE LETTER', 'Smiles', 'Medium', 'Low', 'Medium'],
        Cancer: ['Slippers', 'fancy coffee', 'SEND THEM A CUTE MESSAGE', 'Surprises', 'High', 'High', 'High'],
        Capricorn: ['Home Decor', 'Gym', 'GET THEM THEIR FAVORITE SNACK', 'Massage', 'High', 'High', 'High'],
        Virgo: ['Diffuser', 'Movie night', 'BINGE YOUR FAVORITE SHOW TOGETHER', 'Make a music video', 'Medium', 'High', 'Medium'],
        Scorpio: ['Dessert', 'rock-climbing', 'TAKE THEM OUT TO DINNER', 'Gifts', 'Medium', 'High', 'High'],
        Saggitarius: ['Pizza', 'apple-picking', 'COZY MOVIE NIGHT IN', 'Honesty', 'Low', 'Low', 'Medium'],
        Taurus: ['Clothes', 'horseback riding', 'MAKE THEM DINNER', 'Love', 'High', 'High', 'High'],
        Gemini: ['Bath Robe and Wine', 'Netflix and Pizza', 'BREAKFAST IN BED', 'Care', 'Medium', 'Low', 'Medium'],
        Pisces: ['Chocolate', 'Ski Trip', 'LIGHTEN THEIR LOAD', 'Food', 'High', 'Medium', 'Medium'],
        Libra: ['Shoes', 'Board Game', 'SHOW APPRECIATION', 'Cooking', 'Low', 'Low', 'Low'],
        Leo: ['Blanket', 'Picnic', 'BE THEIR BIGGEST SUPPORTER', 'Motivation', 'Medium', 'Low', 'Medium']
    },
    Aries: {
        Aries: ['Book/movie series', 'Sporting event', 'WORDS OF AFFIRMATION', 'Movie night', 'High', 'High', 'High'],
        Aquarius: ['Ski Pass', 'Hiking', 'CELEBRATE WHAT MAKE THEM SPECIAL', 'Helping', 'High', 'High', 'High'],
        Cancer: ['SunfLowers', 'Dinner', 'BE SPONTANEOUS', 'Hugs', 'Low', 'Low', 'Low'],
        Capricorn: ['Tickets to a show', 'Brunch', 'DINNER NIGHT IN', 'Dessert', 'Low', 'Low', 'Low'],
        Scorpio: ['Bubble bath soap', 'campfire', 'BINGE YOUR FAVORITE SHOW TOGETHER', 'Breakfast', 'Low', 'High', 'Medium'],
        Saggitarius: ['Cheese board', 'spa night', 'ORDER TAKE OUT', 'Chocolates', 'High', 'High', 'High'],
        Taurus: ['Subscription to a streaming service', 'day trip', 'COOK TOGETHER', 'Vacation', 'Medium', 'Low', 'Low'],
        Gemini: ['Purse', 'new skill', 'ORDER PIZZA IN ', 'Family Time', 'High', 'High', 'High'],
        Pisces: ['Tumbler', 'shopping', 'ACTS OF SERVICE', 'Cooking a meal', 'Medium', 'High', 'Low'],
        Libra: ['Starbucks gift card', 'dance class', 'WORDS OF AFFIRMATION', 'Fresh bakes goods', 'High', 'Medium', 'Medium'],
        Leo: ['Fresh baked cookies', 'volunteer together', 'GIFT GIVING,Candles', 'High', 'High', 'High']

    },
    Aquarius: {
        Aquarius: ['Novelty Mug', 'Concert', 'ACTS OF SERVICE', 'Staycation', 'High', 'High', 'High'],
        Cancer: ['Spa certificate', 'zoo', 'QUALITY TIME', 'Making the bed', 'Medium', 'Low', 'Low'],
        Capricorn: ['An outfit', 'dessert', 'PHYSICAL TOUCH', 'Clean the house', 'Medium', 'Low', 'Low'],
        Scorpio: ['Pair of shoes', 'Star gazing', 'QUALITY TIME', 'Taking their pet on a walk', 'Medium', 'Medium', 'Medium'],
        Saggitarius: ['Hoodie', 'comedy show', 'QUALITY TIME', 'Get along with their family', 'High', 'High', 'High'],
        Taurus: ['Photo frame', 'farmers market', 'ACTS OF SERVICE', 'Plan a trip', 'Medium', 'Low', 'Low'],
        Gemini: ['House plant', 'brewery', 'GIFT GIVING', 'Plan a date', 'High', 'High', 'High'],
        Pisces: ['Artwork', 'karaoke', 'PHYSICAL TOUCH', 'Nice drive', 'Medium', 'High', 'Low'],
        Libra: ['Vase with fLowers', 'bowling', 'ACTS OF SERVICE', 'Beach day', 'High', 'High', 'High'],
        Leo: ['Balloons', 'pool', 'WORDS OF AFFIRMATION', 'Candy', 'Low', 'Medium', 'Medium']
    },
    Cancer: {
        Aquarius: [],
        Cancer: ['Mathcing PJs', 'Duffy boat rental', 'GIFT GIVING', 'Workout gear', 'High', 'High', 'High'],
        Capricorn: ['Stuffed animal', 'stay-cation', 'LISTEN ACTIVELY', 'Spa day', 'Medium', 'High', 'Medium'],
        Scorpio: ['Massager', 'wine tour', 'LEAVE A LOVE NOTE', 'Cuddles', 'High', 'High', 'High'],
        Saggitarius: ['Aapron', 'drive-in movie', 'TAKE OUT AND A MOVIE', 'Scavenger hunt', 'Medium', 'Medium', 'Low'],
        Taurus: ['Music playlist', 'live show', 'LEARN A HOBBY TOGETHER', 'Surprise party', 'High', 'High', 'High'],
        Gemini: ['Cooking Supplies', 'double date', 'TAKE A TRIP TOGETHER', 'Game night', 'Medium', 'Low', 'Low'],
        Pisces: ['Boots', 'kayaking', 'SPEND THE DAY AT THE BEACH', 'Cocktails', 'High', 'High', 'High'],
        Libra: ['Baked goods', 'swimming', 'ACTS OF SERVICE', 'Cheese board', 'Medium', 'Low', 'Low'],
        Leo: ['Paint by numbers kit', 'cook together', 'WORDS OF AFFIRMATION', 'Pick them up/drop them off to work', 'Low', 'Medium', 'Medium']
    },
    Capricorn: {
        Aquarius: [],
        Cancer: [],
        Capricorn: ['Weighted blanket', 'Candle-lit dinner', 'PHYSICAL TOUCH', 'A weekend getaway', 'High', 'High', 'High'],
        Scorpio: ['Puzzle', 'arcade', 'GIFT GIVING', 'FLower delivery', 'High', 'High', 'High'],
        Saggitarius: ['Board game', 'camping', 'QUALITY TIME', 'Cute notes', 'Medium', 'Low', 'Low'],
        Taurus: ['Tickets to a sporting event', 'dinner party', 'PHYSICAL TOUCH,Massage', 'High', 'High', 'High'],
        Gemini: ['Rollerskates', 'movie', 'QUALITY TIME', 'Make a playlist', 'Medium', 'Low', 'Low'],
        Pisces: ['New phone case', 'sports game', 'ACTS OF SERVICE', 'Send music', 'High', 'High', 'High'],
        Libra: ['Headphones', 'laser tag', 'WORDS OF AFFIRMATION', 'Write a song', 'Low', 'Medium', 'Medium'],
        Leo: ['Exercise clothes', 'go-karts', 'GIFT GIVING', 'Buy a new outfit', 'Medium', 'Medium', 'High']
    },
    Scorpio: {
        Aquarius: [],
        Cancer: [],
        Capricorn: [],
        Scorpio: ['French press', 'Picnic at the beach', 'ACTS OF SERVICE', 'Pretty bottle of champagne', 'High', 'High', 'High'],
        Saggitarius: ['Pottery lesson', 'sunset hike', 'PHYSICAL TOUCH', 'Tickets to a theme park', 'High', 'Medium', 'Low'],
        Taurus: ['Private cooking lesson', 'yoga', 'ACTS OF SERVICE', 'Drive in movie date', 'Low', 'High', 'High'],
        Gemini: ['Wine and paint night', 'dog park', 'WORDS OF AFFIRMATION', 'Make a dance', 'Medium', 'Low', 'Low'],
        Pisces: ['Spa certficate', 'ice cream', 'LIGHTEN THEIR LOAD', 'Write a letter', 'High', 'Low', 'High'],
        Libra: ['Night at a whole', 'Fun adventure', 'SHOW APPRECIATION', 'Draw a bath', 'High', 'Low', 'Medium'],
        Leo: ['Weekend getaway', 'Game night', 'BE THEIR BIGGEST SUPPORTER', 'Candle lit dinner', 'High', 'Medium', 'High']
    },
    Saggitarius: {
        Aquarius: [],
        Cancer: [],
        Capricorn: [],
        Scorpio: [],
        Saggitarius: ['Flask', 'Paint night', 'QUALITY TIME', 'Chocolate covered strawberries', 'Medium', 'High', 'Medium'],
        Taurus: ['Book', 'vineyard', 'CELEBRATE WHAT MAKE THEM SPECIAL', 'Hot air balloon ride', 'Medium', 'High', 'Low'],
        Gemini: ['Sunglasses', 'Wine tour', 'BE SPONTANEOUS', 'Matching jewelry', 'Low', 'Medium', 'Medium'],
        Pisces: ['Watch', 'sailboat', 'DINNER NIGHT IN', 'Rent a cool car', 'Medium', 'Low', 'Low'],
        Libra: ['Snuggie', 'party', 'BINGE YOUR FAVORITE SHOW TOGETHER', 'Carnical date', 'High', 'Medium', 'High'],
        Leo: ['Puppy', 'flea market', 'ORDER TAKE OUT', 'Make them overcome a fear', 'Medium', 'High', 'High']
    },
    Taurus: {
        Aquarius: [],
        Cancer: [],
        Capricorn: [],
        Taurus: ['Tie', 'Rage room', 'PHYSICAL TOUCH', 'Bouqet of their favorite fLowers', 'High', 'High', 'High'],
        Scorpio: [],
        Saggitarius: [],
        Gemini: ['Kitten', 'balloon fight', 'COOK TOGETHER', 'Spontaneous road trip', 'Low', 'Medium', 'Medium'],
        Pisces: ['Trip to the zoo', 'forest run', 'ORDER PIZZA IN', 'Visit a cat cafe', 'High', 'High', 'High'],
        Libra: ['Trip to the aquarium', 'amusement park', 'MAKE THEM DINNER', 'Send random cute texts', 'Low', 'Low', 'Medium'],
        Leo: ['Reservation at a rage room', 'sky diving', 'BREAKFAST IN BED', 'Breakfast in bed', 'Medium', 'Medium', 'Medium']
    },
    Gemini: {
        Aquarius: [],
        Cancer: [],
        Capricorn: [],
        Gemini: ['Belt', 'Bottomless mimosas', 'ORDER PIZZA IN', 'Digital painting', 'Medium', 'High', 'Medium'],
        Scorpio: [],
        Saggitarius: [],
        Taurus: [],
        Pisces: ['Reservation at an escape room', 'BBQ', 'LIGHTEN THEIR LOAD', 'Subscription service', 'High', 'High', 'Low'],
        Libra: ['New cell phone', 'spa day', 'SHOW APPRECIATION', 'Candle making class', 'Medium', 'High', 'High'],
        Leo: ['Shopping spree', 'Massages', 'BE THEIR BIGGEST SUPPORTER', 'Scented candles', 'Medium', 'Low', 'High']
    },
    Pisces: {
        Aquarius: [],
        Cancer: [],
        Capricorn: [],
        Scorpio: [],
        Saggitarius: [],
        Taurus: [],
        Gemini: [],
        Pisces: ['Hydroflask', 'Escape room', 'QUALITY TIME', 'Basket of their favorite snacks', 'High', 'High', 'Medium'],
        Libra: ['Knife set', 'Cuddling and food', 'CELEBRATE WHAT MAKE THEM SPECIAL', 'Perfume/Cologne', 'Low', 'Medium', 'Medium'],
        Leo: ['Perfume', 'Dancing', 'BE SPONTANEOUS', 'Make their favorite dessert', 'Medium', 'Medium', 'Medium']
    },
    Libra: {
        Aquarius: [],
        Cancer: [],
        Capricorn: [],
        Scorpio: [],
        Saggitarius: [],
        Taurus: [],
        Gemini: [],
        Pisces: [],
        Libra: ['Gift cards', 'Rollerskating', 'COOK TOGETHER', 'Custom puzzle', 'Medium', 'Medium', 'Medium'],
        Leo: ['Cologne', 'Improv Show', 'DINNER NIGHT IN', 'Recreate their favorite movie scene', 'Low', 'Low', 'High']
    },
    Leo: {
        Aquarius: [],
        Cancer: [],
        Capricorn: [],
        Scorpio: [],
        Saggitarius: [],
        Taurus: [],
        Gemini: [],
        Pisces: [],
        Libra: [],
        Leo: ['Movie basket', 'Ice skating', 'ORDER TAKE OUT', 'Choreograph a dance', 'High', 'High', 'High']
    }
}