export const cardsAndMeaning = [
    [require("../../assets/Cards/CardsFront/Ace_of_Cups.png"), require("../../assets/Cards/CardsMeaning/Ace_of_Cups_A_L.png")],
    [require("../../assets/Cards/CardsFront/Ace_of_Pentacles.png"), require("../../assets/Cards/CardsMeaning/Ace_of_Pentacles_A_L.png")],
    [require("../../assets/Cards/CardsFront/Ace_of_Wands.png"), require("../../assets/Cards/CardsMeaning/Ace_of_Wands_A_L.png")],
    [require("../../assets/Cards/CardsFront/Ace_of_Swords.png"), require("../../assets/Cards/CardsMeaning/Ace_of_Swords_A_L.png")],
    [require("../../assets/Cards/CardsFront/Death.png"), require("../../assets/Cards/CardsMeaning/Death_A_L.png")],
    [require("../../assets/Cards/CardsFront/Eight_of_Pentacles.png"),  require("../../assets/Cards/CardsMeaning/Eight_of_Pentacles_A_L.png")],
    [require("../../assets/Cards/CardsFront/Eight_of_Wands.png"), require("../../assets/Cards/CardsMeaning/Eight_of_Wands_A_L.png")],
    //[require("./assets/Cards/CardsFront/Eight_of_Cups.png"), require("./assets/Cards/CardsMeaning/Eight_of_Cups_A_L.png")],
    [require("../../assets/Cards/CardsFront/Eight_of_Swords.png"), require("../../assets/Cards/CardsMeaning/Eight_of_Swords_A_L.png")],
    [require("../../assets/Cards/CardsFront/Five_of_Pentacles.png"), require("../../assets/Cards/CardsMeaning/Five_of_Pentacles_A_L.png")],
    [require("../../assets/Cards/CardsFront/Five_of_Wands.png"), require("../../assets/Cards/CardsMeaning/Five_of_Wands_A_L.png")],
    [require("../../assets/Cards/CardsFront/Five_of_Cups.png"), require("../../assets/Cards/CardsMeaning/Five_of_Cups_A_L.png")],
    [require("../../assets/Cards/CardsFront/Five_of_Swords.png"), require("../../assets/Cards/CardsMeaning/Five_of_Swords_A_L.png")],
    [require("../../assets/Cards/CardsFront/Four_of_Pentacles.png"), require("../../assets/Cards/CardsMeaning/Four_of_Pentacles_A_L.png")],
    [require("../../assets/Cards/CardsFront/Four_of_Wands.png"), require("../../assets/Cards/CardsMeaning/Four_of_Wands_A_L.png")],
    [require("../../assets/Cards/CardsFront/Four_of_Cups.png"), require("../../assets/Cards/CardsMeaning/Four_of_Cups_A_L.png")],
    [require("../../assets/Cards/CardsFront/Four_of_Swords.png"), require("../../assets/Cards/CardsMeaning/Four_of_Swords_A_L.png")],
    //[require("./assets/Cards/CardsFront/High_Priestest.png"), require("./assets/Cards/CardsMeaning/High_Priestest_A_L.png")],
    [require("../../assets/Cards/CardsFront/Judgement.png"), require("../../assets/Cards/CardsMeaning/Judgement_A_L.png")],
    [require("../../assets/Cards/CardsFront/Justice.png"), require("../../assets/Cards/CardsMeaning/Justice_A_L.png")],
    [require("../../assets/Cards/CardsFront/King_of_Cups.png"), require("../../assets/Cards/CardsMeaning/King_of_Cups_A_L.png")],
    [require("../../assets/Cards/CardsFront/King_of_Pentacles.png"), require("../../assets/Cards/CardsMeaning/King_of_Pentacles_A_L.png")],
    [require("../../assets/Cards/CardsFront/King_of_Swords.png"), require("../../assets/Cards/CardsMeaning/King_of_Swords_A_L.png")],
    [require("../../assets/Cards/CardsFront/Knight_of_Cups.png"), require("../../assets/Cards/CardsMeaning/Knight_of_Cups_A_L.png")],
    [require("../../assets/Cards/CardsFront/Knight_of_Pentacles.png"),  require("../../assets/Cards/CardsMeaning/Knight_of_Pentacles_A_L.png")],
    [require("../../assets/Cards/CardsFront/Knight_of_Swords.png"), require("../../assets/Cards/CardsMeaning/Knight_of_Swords_A_L.png")],
    //[require("./assets/Cards/CardsFront/Magicians.png"), require("./assets/Cards/CardsMeaning/Magicans_A_L.png")],
    [require("../../assets/Cards/CardsFront/Nine_of_Pentacles.png"), require("../../assets/Cards/CardsMeaning/Nine_of_Pentacles_A_L.png")],
    [require("../../assets/Cards/CardsFront/Nine_of_Wands.png"), require("../../assets/Cards/CardsMeaning/Nine_of_Wands_A_L.png")],
    [require("../../assets/Cards/CardsFront/Nine_of_Cups.png"), require("../../assets/Cards/CardsMeaning/Nine_of_Cups_A_L.png")],
    [require("../../assets/Cards/CardsFront/Nine_of_Swords.png"), require("../../assets/Cards/CardsMeaning/Nine_of_Swords_A_L.png")],
    //[require("./assets/Cards/CardsFront/Page_of_Swords.png"), require("./assets/Cards/CardsMeaning/Pgae_of_Swords_A_L.png")],
    [require("../../assets/Cards/CardsFront/Queen_of_Cups.png"), require("../../assets/Cards/CardsMeaning/Queen_of_Cups_A_L.png")],
    [require("../../assets/Cards/CardsFront/Queen_of_Pentacles.png"),  require("../../assets/Cards/CardsMeaning/Queen_of_Pentacles_A_L.png")],
    [require("../../assets/Cards/CardsFront/Queen_of_Swords.png"), require("../../assets/Cards/CardsMeaning/Queen_of_Swords_A_L.png")],
    [require("../../assets/Cards/CardsFront/Seven_of_Pentacles.png"),  require("../../assets/Cards/CardsMeaning/Seven_of_Pentacles_A_L.png")],
    [require("../../assets/Cards/CardsFront/Seven_of_Wands.png"), require("../../assets/Cards/CardsMeaning/Seven_of_Wands_A_L.png")],
    [require("../../assets/Cards/CardsFront/Seven_of_Cups.png"), require("../../assets/Cards/CardsMeaning/Seven_of_Cups_A_L.png")],
    [require("../../assets/Cards/CardsFront/Seven_of_Swords.png"), require("../../assets/Cards/CardsMeaning/Seven_of_Swords_A_L.png")],
    [require("../../assets/Cards/CardsFront/Six_of_Pentacles.png"), require("../../assets/Cards/CardsMeaning/Six_of_Pentacles_A_L.png")],
    [require("../../assets/Cards/CardsFront/Six_of_Wands.png"), require("../../assets/Cards/CardsMeaning/Six_of_Wands_A_L.png")],
    [require("../../assets/Cards/CardsFront/Six_of_Cups.png"), require("../../assets/Cards/CardsMeaning/Six_of_Cups_A_L.png")],
    [require("../../assets/Cards/CardsFront/Six_of_Swords.png"), require("../../assets/Cards/CardsMeaning/Six_of_Swords_A_L.png")],
    [require("../../assets/Cards/CardsFront/Strength.png"), require("../../assets/Cards/CardsMeaning/Strength_A_L.png")],
    //[require("./assets/Cards/CardsFront/Sun_card.png"), require("./assets/Cards/CardsMeaning/Sun_Card_A_L.png")],
    [require("../../assets/Cards/CardsFront/The_Star.png"), require("../../assets/Cards/CardsMeaning/The_Star_A_L.png")],
    [require("../../assets/Cards/CardsFront/Temperance.png"), require("../../assets/Cards/CardsMeaning/Temperance_A_L.png")],
    [require("../../assets/Cards/CardsFront/Ten_of_Pentacles.png"), require("../../assets/Cards/CardsMeaning/Ten_of_Pentacles_A_L.png")],
    [require("../../assets/Cards/CardsFront/Ten_of_Wands.png"), require("../../assets/Cards/CardsMeaning/Ten_of_Wands_A_L.png")],
    [require("../../assets/Cards/CardsFront/Ten_of_Cups.png"), require("../../assets/Cards/CardsMeaning/Ten_of_Cups_A_L.png")],
    [require("../../assets/Cards/CardsFront/Ten_of_Swords.png"), require("../../assets/Cards/CardsMeaning/Ten_of_Swords_A_L.png")],
    [require("../../assets/Cards/CardsFront/The_Chariot.png"), require("../../assets/Cards/CardsMeaning/The_Chariot_A_L.png")],
    [require("../../assets/Cards/CardsFront/The_Devil.png"), require("../../assets/Cards/CardsMeaning/The_Devil_A_L.png")],
    [require("../../assets/Cards/CardsFront/The_Emperor.png"), require("../../assets/Cards/CardsMeaning/The_Emperor_A_L.png")],
    [require("../../assets/Cards/CardsFront/The_Empress.png"), require("../../assets/Cards/CardsMeaning/The_Empress_A_L.png")],
    [require("../../assets/Cards/CardsFront/The_Fool.png"), require("../../assets/Cards/CardsMeaning/The_Fool_A_L.png")],
    [require("../../assets/Cards/CardsFront/The_Hierophant.png"), require("../../assets/Cards/CardsMeaning/The_Hierophant_A_L.png")],
    [require("../../assets/Cards/CardsFront/The_Hanged_Man.png"), require("../../assets/Cards/CardsMeaning/The_Hanged_Man_A_L.png")],
    [require("../../assets/Cards/CardsFront/The_Hermit.png"), require("../../assets/Cards/CardsMeaning/The_Hermit_A_L.png")],
    [require("../../assets/Cards/CardsFront/The_Lovers.png"), require("../../assets/Cards/CardsMeaning/The_Lovers_A_L.png")],
    [require("../../assets/Cards/CardsFront/The_Moon.png"), require("../../assets/Cards/CardsMeaning/The_Moon_A_L.png")],
    [require("../../assets/Cards/CardsFront/The_Tower.png"), require("../../assets/Cards/CardsMeaning/The_Tower_A_L.png")],
    [require("../../assets/Cards/CardsFront/The_World.png"), require("../../assets/Cards/CardsMeaning/The_World_A_L.png")],
    [require("../../assets/Cards/CardsFront/Three_of_Pentacles.png"),  require("../../assets/Cards/CardsMeaning/Three_of_Pentacles_A_L.png")],
    [require("../../assets/Cards/CardsFront/Three_of_Wands.png"), require("../../assets/Cards/CardsMeaning/Three_of_Wands_A_L.png")],
    [require("../../assets/Cards/CardsFront/Three_of_Cups.png"), require("../../assets/Cards/CardsMeaning/Three_of_Cups_A_L.png")],
    [require("../../assets/Cards/CardsFront/Three_of_Swords.png"), require("../../assets/Cards/CardsMeaning/Three_of_Swords_A_L.png")],
    [require("../../assets/Cards/CardsFront/Two_of_Pentacles.png"), require("../../assets/Cards/CardsMeaning/Two_of_Pentacles_A_L.png")],
    [require("../../assets/Cards/CardsFront/Two_of_Wands.png"), require("../../assets/Cards/CardsMeaning/Two_of_Wands_A_L.png")],
    [require("../../assets/Cards/CardsFront/Two_of_Cups.png"), require("../../assets/Cards/CardsMeaning/Two_of_Cups_A_L.png")],
    [require("../../assets/Cards/CardsFront/Two_of_Swords.png"), require("../../assets/Cards/CardsMeaning/Two_of_Swords_A_L.png")],
    [require("../../assets/Cards/CardsFront/Wheel_of_Fortune.png"), require("../../assets/Cards/CardsMeaning/Wheel_of_Fortune_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Ace_of_Cups_R.png"),require("../../assets/Cards/CardsMeaning/Ace_of_Cups_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Ace_of_Pentacles_R.png"), require("../../assets/Cards/CardsMeaning/Ace_of_Pentacles_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Ace_of_Wands_R.png"),require("../../assets/Cards/CardsMeaning/Ace_of_Wands_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Ace_of_Swords_R.png"), require("../../assets/Cards/CardsMeaning/Ace_of_Swords_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Death_R.png"),require("../../assets/Cards/CardsMeaning/Death_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Eight_of_Pentacles_R.png"), require("../../assets/Cards/CardsMeaning/Eight_of_Pentacles_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Eight_of_Wands_R.png"), require("../../assets/Cards/CardsMeaning/Eight_of_Wands_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Eight_of_Cups_R.png"), require("../../assets/Cards/CardsMeaning/Eight_of_Cups_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Eight_of_Swords_R.png"), require("../../assets/Cards/CardsMeaning/Eight_of_Swords_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Five_of_Pentacles_R.png"), require("../../assets/Cards/CardsMeaning/Five_of_Pentacles_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Five_of_Wands_R.png"), require("../../assets/Cards/CardsMeaning/Five_of_Wands_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Five_of_Cups_R.png"),require("../../assets/Cards/CardsMeaning/Five_of_Cups_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Five_of_Swords_R.png"), require("../../assets/Cards/CardsMeaning/Five_of_Swords_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Four_of_Pentacles_R.png"), require("../../assets/Cards/CardsMeaning/Four_of_Pentacles_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Four_of_Wands_R.png"), require("../../assets/Cards/CardsMeaning/Four_of_Wands_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Four_of_Cups_R.png"),require("../../assets/Cards/CardsMeaning/Four_of_Cups_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Four_of_Swords_R.png"), require("../../assets/Cards/CardsMeaning/Four_of_Swords_A_L.png")],
    //[require("./assets/Cards/CardsFrontReversed/High_Priestest_R.png"), require("./assets/Cards/CardsMeaning/High_Priestest_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Judgement_R.png"),require("../../assets/Cards/CardsMeaning/Judgement_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Justice_R.png"),require("../../assets/Cards/CardsMeaning/Justice_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/King_of_Cups_R.png"),require("../../assets/Cards/CardsMeaning/King_of_Cups_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/King_of_Pentacles_R.png"), require("../../assets/Cards/CardsMeaning/King_of_Pentacles_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/King_of_Swords_R.png"), require("../../assets/Cards/CardsMeaning/King_of_Swords_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Knight_of_Cups_R.png"), require("../../assets/Cards/CardsMeaning/Knight_of_Cups_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Knight_of_Pentacles_R.png"), require("../../assets/Cards/CardsMeaning/Knight_of_Pentacles_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Knight_of_Swords_R.png"), require("../../assets/Cards/CardsMeaning/Knight_of_Swords_A_L.png")],
    //[require("./assets/Cards/CardsFrontReversed/Magicians_R.png"),require("./assets/Cards/CardsMeaning/Magicians_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Nine_of_Pentacles_R.png"), require("../../assets/Cards/CardsMeaning/Nine_of_Pentacles_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Nine_of_Wands_R.png"), require("../../assets/Cards/CardsMeaning/Nine_of_Wands_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Nine_of_Cups_R.png"),require("../../assets/Cards/CardsMeaning/Nine_of_Cups_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Nine_of_Swords_R.png"), require("../../assets/Cards/CardsMeaning/Nine_of_Swords_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Page_of_Swords_R.png"), require("../../assets/Cards/CardsMeaning/Page_of_Swords_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Queen_of_Cups_R.png"), require("../../assets/Cards/CardsMeaning/Queen_of_Cups_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Queen_of_Pentacles_R.png"), require("../../assets/Cards/CardsMeaning/Queen_of_Pentacles_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Queen_of_Swords_R.png"), require("../../assets/Cards/CardsMeaning/Queen_of_Swords_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Seven_of_Pentacles_R.png"), require("../../assets/Cards/CardsMeaning/Seven_of_Pentacles_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Seven_of_Wands_R.png"), require("../../assets/Cards/CardsMeaning/Seven_of_Wands_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Seven_of_Cups_R.png"), require("../../assets/Cards/CardsMeaning/Seven_of_Cups_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Seven_of_Swords_R.png"), require("../../assets/Cards/CardsMeaning/Seven_of_Swords_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Six_of_Pentacles_R.png"), require("../../assets/Cards/CardsMeaning/Six_of_Pentacles_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Six_of_Wands_R.png"),require("../../assets/Cards/CardsMeaning/Six_of_Wands_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Six_of_Cups_R.png"),require("../../assets/Cards/CardsMeaning/Six_of_Cups_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Six_of_Swords_R.png"), require("../../assets/Cards/CardsMeaning/Six_of_Swords_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Strength_R.png"),require("../../assets/Cards/CardsMeaning/Strength_A_L.png")],
    //[require("./assets/Cards/CardsFrontReversed/Sun_card_R.png"),require("./assets/Cards/CardsMeaning/Sun_card_A_L.png")],
    //[require("./assets/Cards/CardsFrontReversed/The_Star_R.png"),require("./assets/Cards/CardsMeaning/The_Star_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Temperance_R.png"),require("../../assets/Cards/CardsMeaning/Temperance_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Ten_of_Pentacles_R.png"), require("../../assets/Cards/CardsMeaning/Ten_of_Pentacles_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Ten_of_Wands_R.png"),require("../../assets/Cards/CardsMeaning/Ten_of_Wands_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Ten_of_Cups_R.png"),require("../../assets/Cards/CardsMeaning/Ten_of_Cups_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Ten_of_Swords_R.png"), require("../../assets/Cards/CardsMeaning/Ten_of_Swords_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/The_Chariot_R.png"),require("../../assets/Cards/CardsMeaning/The_Chariot_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/The_Devil_R.png"),require("../../assets/Cards/CardsMeaning/The_Devil_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/The_Emperor_R.png"),require("../../assets/Cards/CardsMeaning/The_Emperor_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/The_Empress_R.png"),require("../../assets/Cards/CardsMeaning/The_Empress_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/The_Fool_R.png"),require("../../assets/Cards/CardsMeaning/The_Fool_A_L.png")],
    //[require("./assets/Cards/CardsFrontReversed/The_HIEROPHANT_R.png"), require("./assets/Cards/CardsMeaning/The_Hierophant_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/The_Hanged_Man_R.png"), require("../../assets/Cards/CardsMeaning/The_Hanged_Man_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/The_Hermit_R.png"), require("../../assets/Cards/CardsMeaning/The_Hermit_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/The_Lovers_R.png"), require("../../assets/Cards/CardsMeaning/The_Lovers_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/The_Moon_R.png"), require("../../assets/Cards/CardsMeaning/The_Moon_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/The_Tower_R.png"), require("../../assets/Cards/CardsMeaning/The_Tower_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/The_World_R.png"), require("../../assets/Cards/CardsMeaning/The_World_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Three_of_Pentacles_R.png"), require("../../assets/Cards/CardsMeaning/Three_of_Pentacles_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Three_of_Wands_R.png"), require("../../assets/Cards/CardsMeaning/Three_of_Wands_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Three_of_Cups_R.png"), require("../../assets/Cards/CardsMeaning/Three_of_Cups_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Three_of_Swords_R.png"), require("../../assets/Cards/CardsMeaning/Three_of_Swords_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Two_of_Pentacles_R.png"), require("../../assets/Cards/CardsMeaning/Two_of_Pentacles_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Two_of_Wands_R.png"), require("../../assets/Cards/CardsMeaning/Two_of_Wands_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Two_of_Cups_R.png"), require("../../assets/Cards/CardsMeaning/Two_of_Cups_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Two_of_Swords_R.png"), require("../../assets/Cards/CardsMeaning/Two_of_Swords_A_L.png")],
    [require("../../assets/Cards/CardsFrontReversed/Wheel_of_Fortune_R.png"), require("../../assets/Cards/CardsMeaning/Wheel_of_Fortune_A_L.png")]
];
